### ISSUE TITLE
adding this package leads to error

### ISSUE THREAD

**Issue by c33s** [core23/GDPRBundle#563]
#### Packages

symfony 4.4 application
```
$ composer show --latest
---snip---
sonata-project/block-bundle             4.7.0            4.7.0            Symfony SonataBlockBundle
sonata-project/cache                    2.2.0            2.2.0            Cache library
sonata-project/doctrine-extensions      1.14.0           1.14.0           Doctrine2 behavioral extensions
sonata-project/form-extensions          1.11.0           1.11.0           Symfony form extensions
sonata-project/twig-extensions          1.9.0            1.9.0            Sonata twig extensions
---snip---
```

#### PHP version

```
$ php -v
7.4
```

## Subject

adding this package to me previously working project leads to an error  (directly after installing it with composer, while `cache:clear` is called).

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
!!
!!     The service "sonata.twig.template_extension" has a dependency on a non-existent service "sonata.doctrine.model.adapter.chain".
!!
!!
!!
Script @auto-scripts was called via post-update-cmd
```

also tried to completly delete the cache folder.

**Comment by core23** [comment]
Do you use flex? Otherwise you have to add the `SonataDoctrineBundle` to your bundle config.

Btw. this is not a problem of the `NucleosGDPRBundle`.

**Comment by core23** [comment]
Should be fixed with https://github.com/sonata-project/SonataBlockBundle/pull/958

**Comment by c33s** [comment]
yes i use flex.

ide shows a missing class for `SonataTwigSymfonyBundle`. the class alias i think.

![image](https://user-images.githubusercontent.com/649209/136722055-411d3f39-ed06-458b-b91f-977467faa9ae.png)


added the following manually to `bundles.php`
```
    # added by flex
    Sonata\Twig\Bridge\Symfony\SonataTwigSymfonyBundle::class => ['all' => true],
    Nucleos\GDPRBundle\NucleosGDPRBundle::class => ['all' => true],
    # added manually
    Sonata\Doctrine\Bridge\Symfony\SonataDoctrineBundle::class => ['all' => true],
    Sonata\BlockBundle\SonataBlockBundle::class => ['all' => true],
```

added the following line to my app.js
`app.js` (webpack encore):
```
const initGdprPopup = require('../../vendor/nucleos/gdpr-bundle/assets/js/GdprPopup.js')
```
now it works partially. the js is not triggering. 

would be awesome to have a little more documentation.
